branch-defaults:
  default:
    environment: udagram-api-env
    group_suffix: null
  main:
    environment: udagram-api-dev
environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null
  udagram-api-env:
    branch: main
    repository: udagramapi
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
